### ISSUE TITLE
are you planning to light theme for this

### ISSUE THREAD

**Issue by Adityapanther** [anuraghazra/convoychat#50]
Hi Anurag,
                  Are you planning to add light theme mode on this project.

**Comment by widelachie** [comment]
why would you want to burn your eyes out

**Comment by Adityapanther** [comment]
dude, I don't want to burn my eyes out. I am thinking about user who prefer light theme to use.

**Comment by anuraghazra** [comment]
@Adityapanther no i 'm not planning for light theme although it would not be very hard to change the theme.

**Comment by Adityapanther** [comment]
thanks @anuraghazra to clear my doubt or thought.
